### ISSUE TITLE
Error starting Adapter (v1.0.1)

### ISSUE THREAD

**Issue by daNick73** [SebastianSchultz/ioBroker.enet#9] opened 2019-02-09 18:34 UTC
Hi

I am trying to reinstall ioBroker, moving to a new HW platform.

It works with the GATEWAY in the current production

eNet used to work, but V1.0.1 and V1.0.0 cause issues

in v.1.0.0, the adapter seems to work, but the traffic light remains yellow.

in v1.0.1, the log keeps showing:
instance system.adapter.enet.0 terminated with code 10 (Cannot find start file of adapter)

**Comment by SebastianSchultz** [comment] 2019-02-09 18:58
Hello,

the eNet Server is currently not supported. 
I'm still working on it.

**Comment by daNick73** [comment] 2019-02-09 21:21
Hi

1. THX THX THX!!!

2. am using the GATEWAY setting and it doesn’t work.

What is the last version BEFORE 1.0.0, so I could manually install that one?

Again: THX!

Nico

Sebastian Schultz <notifications@github.com> schrieb am Sa. 9. Feb. 2019 um
19:58:

**Comment by SebastianSchultz** [comment] 2019-02-10 11:57
1.0.1 is the current working Version.
I had installed it via Github URL and it works without any errors.

Can you please try to uninstall the Adapter completely and install it via Github URL?
If this doesn't work I Need a debug log.

**Comment by daNick73** [comment] 2019-02-13 18:47
Hi

Thank you for your efforts. 
versions 1.0.0 and 1.0.1 still dont work for me, BUT: 0.0.4 does it, so I am fine with 

sudo iobroker stop
sudo npm install iobroker.enet@0.0.4 --production
sudo iobroker upload enet
sudo iobroker start

THX

**Comment by RainerX** [comment] 2019-05-12 20:58
Hi,

are there any news on this topic? I had the same problem with and switched back to 0.0.4 to solve it, but would rather like to use the newest version.

Thanks,
Rainer

**Comment by SebastianSchultz** [comment] 2019-05-13 05:41
Do you get any error messages in log if you set the adapter in debug mode?
Do you run the adapter in gateway or server mode?

**Comment by RainerX** [comment] 2019-05-13 18:47
Thanks for your help!
Adapter is running in gateway mode. Error message is the same as daNick73 reported:
instance system.adapter.enet.0 terminated with code 10 (Cannot find start file of adapter)

During adapter installation I get this warning (don't know if it helps):

$ ./iobroker add enet  --host RaspberryPi01
NPM version: 6.4.1
npm install iobroker.enet --production --save --prefix "/opt/iobroker" (System call)
npm WARN enoent ENOENT: no such file or directory, open '/opt/iobroker/node_modules/follow-redirects/package.json'

**Comment by SebastianSchultz** [comment] 2019-05-13 19:34
I don't know what's wrong at your installation I had done the following:

- Uninstalled ALL instances of the eNet adapter
- Uninstalles the eNet adapter from iobroker
- Installed the eNet adapter from the following Github URL: https://github.com/SebastianSchultz/ioBroker.enet
- Added a new instance of the eNet adapter and configured it

The adapter ist starting and working without any error messages...

Can you please try this?

**Comment by RainerX** [comment] 2019-05-13 21:57
Thanks, but this did not solve the problem.

I then tried the following (see https://forum.iobroker.net/topic/7198/adapter-cannot-find-start-file):
1. Rename main.js in /opt/iobroker/node_modules/iobroker.enet to mainorg.js
2. Add a file main.js in this directory which contains just this line:
`require('./mainorg');`
3. Restarted iobroker and created a new instance of enet
=> No more errors, adapter seems to be running

Does this give you a hint to solve this issue? There is obviously a problem with resolving path names.

**Comment by SebastianSchultz** [comment] 2019-05-13 22:41
Do you use the adapter / ioBroker on a windows machine or a raspberry?
Or something other system?

**Comment by RainerX** [comment] 2019-05-13 23:24
On a Raspberry Pi3+. 
Am 14.05.19, 00:41, Sebastian Schultz <notifications@github.com> schrieb:
Do you use the adapter / ioBroker on a windows machine or a raspberry?
Or something other system?

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/SebastianSchultz/ioBroker.enet/issues/9?email_source=notifications\u0026email_token=AMBXBRSZF4WKMMDC2LHJ4GLPVHVARA5CNFSM4GWKWJW2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVJYKLY#issuecomment-492012847",
"url": "https://github.com/SebastianSchultz/ioBroker.enet/issues/9?email_source=notifications\u0026email_token=AMBXBRSZF4WKMMDC2LHJ4GLPVHVARA5CNFSM4GWKWJW2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODVJYKLY#issuecomment-492012847",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by SebastianSchultz** [comment] 2019-05-13 23:41
Thanks for your input.
It seems a raspberry/linux specific problem...
I think (like you) it's a path resolving issue.

I will investigate this further and implement a solution in the next update,

**Comment by RainerX** [comment] 2019-05-14 10:23
Thanks a lot!

**Comment by daNick73** [comment] 2019-05-14 11:43
Just in case it helps:
My HW platform was also a Raspberry 3

**Comment by SebastianSchultz** [comment] 2019-05-20 17:42
I set the startfile in io-package.json.
Can you please uninstall the adapter and reinstall it here from GitHub url (https://github.com/SebastianSchultz/ioBroker.enet).

Can ou please report if the error still occurs?

**Comment by RainerX** [comment] 2019-05-21 21:36
Yes, thanks, I will do next weekend when I am back at home

**Comment by SebastianSchultz** [comment] 2019-06-06 09:08
Hello,

do you have any update on this issue?

**Comment by RainerX** [comment] 2019-06-11 23:10
Hi,
sorry for my late answer, I did not find time to continue my private projects.
Tonight, I installed the adapter with the modified io-package.json and it runs. 

I still have a problem with my scripts. setState doesn't seem to work any longer. Test script:

console.log(getState("enet.0.channel22.STATE").val);
setState("enet.0.channel22.STATE", true);
console.log(getState("enet.0.channel22.STATE").val);

produces this:

javascript.0 script.js.Test: false
javascript.0 script.js.Test: false

and this warning message:

javascript.0  script.js.Test: setForeignState(id=enet.0.channel22.STATE, state=true)  - was not executed, while debug mode is active

**Comment by SebastianSchultz** [comment] 2019-06-12 14:01
Have you tried to set the value in the objects tab instead in a script?
Because of the periodically readout of the actual values of the channels from the gateway it is possible that this readout overwrites vour value?

**Comment by RainerX** [comment] 2019-06-12 22:11
Yes, I tried to set the value in the objects tab. This doesn't work either.
But: Both run with version 0.0.4 of the adapter, which I am still using use as backup until now.

**Comment by SebastianSchultz** [comment] 2019-06-12 22:15
Have you only replaced io-package.json?
Then that doesn't work.
You have to reinstall the adapter via Github URL. to get it working.
Can you please uninstall the adapter and reinstall it via Github URL?

**Comment by RainerX** [comment] 2019-06-14 10:41
Good point. Of course I installed the complete package, but I am not sure if everything was done in the right way.
So, what is the easiest and safest way to uninstall the old adapter and reinstall the new one from Github URL?

**Comment by SebastianSchultz** [comment] 2019-06-17 07:12
First uninstall all instances of the adapter and the adapter itself via console command "iobroker del enet"
Then on the "adapter" tab click on the Github logo (expert mode enabled) and enter the following url to install from Github: "https://github.com/SebastianSchultz/ioBroker.enet"

That's all :)

**Comment by RainerX** [comment] 2019-06-17 20:01
Ok, thanks. Installation done, created and activated an instance of the adapter. Adapter starts, no errors in the log, so the "Error starting Adapter" seems to be solved.

But when I try to change the STATE of an object in the objects tab (e.g. to true to switch on a light), it is immediately set back to false. So I cannot change any states, just read them out. I guess this is not the intended behavior. At least, with version 0.0.4 this worked.

By the way, during installation I get warnings, see attached file.
[output.txt](https://github.com/SebastianSchultz/ioBroker.enet/files/3298632/output.txt)

**Comment by RainerX** [comment] 2019-06-17 20:05
You wrote before "Because of the periodically readout of the actual values of the channels from the gateway it is possible that this readout overwrites vour value?" Yes, it looks like that, but how can I use the adapter then to control the actors through the gateway?

**Comment by RainerX** [comment] 2019-06-17 20:36
One additional info: With the old version 0.0.4 the behavior is as follows: When I set the STATE of a channel to true, the connected actor (in my case a light) is switched on. The STATE variable immediately switches back to false (my interpretation: it reads out an old value from the gateway), while the actor is still on. After a second or two the STATE variable switches to true (because the STATE variable is now updated in the gateway?) and hence correctly shows the state of the actor. Changing from true to false (in my case switch off the light) shows the same behavior. The behavior is somewhat strange but finally ok, because the actors can be controlled, which is not the case with version 1.0.1. All tests have been done on the objects tab.

Is there a timing problem with version 1.0.1 so that the channel value is not really changed?

**Comment by SebastianSchultz** [comment] 2019-06-18 17:43
Hello Rainer,

I hevae to investigate and test this at my very simple eNet example installation (only one switching actor and 1 blind actor).
Currently I have not much time but I will check it.
I come back to you if I have new information OK?!

**Comment by RainerX** [comment] 2019-06-18 19:10
Sure, thanks a lot. I'll stay on version 0.0.4 until then.

**Comment by SebastianSchultz** [comment] 2019-06-18 22:03
Hello Rainer,

I think I found the bug. A little mistake with big effects :)
an you please reinstall the adapter from the GitHub url and check if it works at your ioBroker installation? Pleaese give me a feedback :)

**Comment by RainerX** [comment] 2019-06-23 15:42
Looks good. The STATE variable still behaves strangely as described above, but I can switch the actors now.  As the object model has changed from version 0.0.4 to version 1.0.1 I have to adapt my scripts, but this is not a big job.

So thanks for the bug fix and your work here!

**Closed** 2019-06-23 17:39 UTC
Labels: bug
